version: '3.7'

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/data
    env_file: ./services/postgres/postgres.env

  pgadmin:
    container_name: pgadmin
    build:
      context: ./services/pgadmin
      dockerfile: Dockerfile
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@serendipity.org.au}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-secret}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    volumes:
      - .:/root/.pgadmin

  jasperreports-server:
    container_name: jasperreports-server
    build:
      context: ./services/jasperreports-server
      dockerfile: Dockerfile
    ports:
      - "11001:8080"
      - "11443:8443"
    volumes:
      - ./license:/usr/local/share/jasperserver/license
      - ./keystore:/usr/local/share/jasperserver/keystore
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: ./services/jasperreports-server/jasper-reports.env
    environment:
      - DB_HOST=postgres
    depends_on:
      - jasperreports-server-cmdline
    command: ["run"]

  jasperreports-server-cmdline:
    container_name: jasperreports-server-cmdline
    build:
      context: ./services/jasperreports-server
      dockerfile: Dockerfile-cmdline
    volumes:
      - ./license:/usr/local/share/jasperserver/license
      - ./keystore:/usr/local/share/jasperserver/keystore
    env_file: ./services/jasperreports-server/jasper-reports.env
    environment:
      - DB_HOST=postgres
      - JRS_LOAD_SAMPLES=true
    depends_on:
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "-t" , "30", "--", "./entrypoint-cmdline-ce.sh", "init"]
